// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCwKIVsMKw7tY4KKUkn2oMPV8bCpBYKw',
    appId: '1:527530510706:web:93ce0e6252cb67b745f5eb',
    messagingSenderId: '527530510706',
    projectId: 'hokkecounter',
    authDomain: 'hokkecounter.firebaseapp.com',
    storageBucket: 'hokkecounter.firebasestorage.app',
    measurementId: 'G-K7F1RYP9K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrF7XnxcYE8NpTAohnk0XQQZL8hSRAD-U',
    appId: '1:527530510706:android:f6eb8e1cc24d9e9345f5eb',
    messagingSenderId: '527530510706',
    projectId: 'hokkecounter',
    storageBucket: 'hokkecounter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4w-UkWG4sGMk7M0HHKPgppBltZP1vG7w',
    appId: '1:527530510706:ios:850d695f216b95b645f5eb',
    messagingSenderId: '527530510706',
    projectId: 'hokkecounter',
    storageBucket: 'hokkecounter.firebasestorage.app',
    iosBundleId: 'com.example.wsd26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4w-UkWG4sGMk7M0HHKPgppBltZP1vG7w',
    appId: '1:527530510706:ios:850d695f216b95b645f5eb',
    messagingSenderId: '527530510706',
    projectId: 'hokkecounter',
    storageBucket: 'hokkecounter.firebasestorage.app',
    iosBundleId: 'com.example.wsd26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMCwKIVsMKw7tY4KKUkn2oMPV8bCpBYKw',
    appId: '1:527530510706:web:d41a492848ba253245f5eb',
    messagingSenderId: '527530510706',
    projectId: 'hokkecounter',
    authDomain: 'hokkecounter.firebaseapp.com',
    storageBucket: 'hokkecounter.firebasestorage.app',
    measurementId: 'G-BQV2GTHCB0',
  );

}